common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 50
  min_messages: warning

development:
  database: bielecki_development
  username:
  password:
  <<: *common

test:
  database: bielecki_test<%= ENV['TEST_ENV_NUMBER'] %>
  <<: *common

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 20 %>
  reaping_frequency: <%= ENV['DB_REAP_FREQ'] || 10 %>
