# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  domain_name: example.com
  secret_key_base: e4611f973dcaaedd169473fbbc2d2fc18444f04c16fbb6f10c5382f9c4accbb52980aa977afaa7da8a33b0ec375ac2fe29e12c78dd0308f90d38e709ccc2ff01

test:
  secret_key_base: d76e50e75264e6ec51d690d861fb8e4f76e39c9e7bc8996ec35adbd023004add60ae54e5201a0ed1192ba690d6fb64193bea662b411c065350895bb9e7606ab7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
